language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install pep8 nose coverage mock"
script:
    - "pep8 --ignore=E501 src/"
    - "nosetests -v --with-cover --cover-min-percentage=80 --cover-package=recore test/"
notifications:
    email: false
